In [1]:
import asyncio
import pandas as pd

import sys
sys.path.append("..")

from src.url_validator import validate_website
from src.typography_scraper import load_page

In [2]:
df = pd.read_csv("../data/processed/sampling_population.csv")
df

,name,website,industry,size,type,city,state,country_code,industry_group
0,~ Fathom ~ Computer and Networking Services,fathomcomputerservices.com,information technology & services,1-10,Self-Owned,Lowell,Massachusetts,US,Technology & Digital
1,♞ knight's path,knightspath.com,computer games,1-10,Privately Held,Laguna Beach,California,US,Technology & Digital
2,0y1 Jewelry Studio,0y1jewelrystudio.com,retail apparel and fashion,1-10,Self-Employed,New,York,US,Commerce & Consumer
3,"1-14 CAV, 3-2 Stryker BDE, US Army",wikipedia.org,armed forces,1K-5K,Government Agency,Lewis-Mcchord,Washington,US,Government & Public Affairs
4,1-800-Biz-Broker | Business Broker in Riversid...,justsoldbiz.com,real estate,1-10,Privately Held,Riverside,California,US,Construction & Real Estate
...,...,...,...,...,...,...,...,...,...
3093203,UNR Civil and Environmental Engineering,unr.edu,civil engineering,11-50,Educational,Reno,Nevada,US,Construction & Real Estate
3093204,Victor School,victorschools.org,higher education,1-10,NaN,Acton,Massachusetts,US,Education
3093205,Virginia Highlands Community College,vhcc.edu,higher education,51-200,Educational,Abingdon,Virginia,US,Education
3093206,Watauga High School,watauga.k12.nc.us,primary and secondary education,51-200,NaN,Boone,North Carolina,US,Education
3093207,Westmont College,westmont.edu,higher education,201-500,Educational,Santa Barbara,California,US,Education

In [3]:
sample = df.sample(40, random_state=42)
sample

,name,website,industry,size,type,city,state,country_code,industry_group
134900,Nigerian Visa & Travel Services,nigerianvisaservices.com,travel arrangements,1-10,Public Company,Houston,Texas,US,Hospitality & Travel
90594,HUSL Digital,husldigital.com,advertising services,11-50,Privately Held,Reston,Virginia,US,Marketing & Communications
1590181,The Bait Shoppe,baitshoppe.com,advertising services,11-50,Privately Held,New York,New York,US,Marketing & Communications
1565349,"Cobalt Sales Management, LLC",cobaltsalesmgt.com,professional training and coaching,1-10,Self-Owned,Tampa,Florida,US,Education
2493185,Med Rank Interactive,medrankinteractive.com,advertising services,1-10,Privately Held,Fort Mill,South Carolina,US,Marketing & Communications
1506761,New Style Motherlode Studio,newstylemotherlode.com,entertainment providers,11-50,NaN,Oakland,California,US,Entertainment & Recreation
680665,Global Fashion Exchange (GFX),globalfashionxchange.org,apparel & fashion,1-10,Partnership,New York,New York,US,Commerce & Consumer
1795787,"Heckscher, Teillon, Terrill & Sager, P.C.",htts.com,law practice,11-50,Privately Held,West Conshohocken,Pennsylvania,US,Legal & Professional Services
2968717,"Write for Me, LLC",writeformellc.com,writing and editing,1-10,Self-Owned,Hammond,Wisconsin,US,Media & Publishing
2619685,MJO Bookkeeper,mjobookkeeper.com,accounting,1-10,Self-Employed,Audubon,Pennsylvania,US,Legal & Professional Services
464143,Kirschner Contractors,kirschnercontractors.com,construction,1-10,Partnership,Kailua,Hawaii,US,Construction & Real Estate
1084064,Dale Feste Automotive,dalefesteautomotive.com,automotive,11-50,NaN,Hopkins,Minnesota,US,Manufacturing & Industrial
1594779,YQ Art,yqart.com,design services,11-50,Privately Held,Riffa,NaN,US,Arts & Design
106208,Swift Prepaid Solutions,swiftprepaid.com,financial services,51-200,Privately Held,Buffalo Grove,Illinois,US,Finance & Insurance
366165,Table Bay Financial,tablebayfinancial.com,insurance,11-50,NaN,Torrance,California,US,Finance & Insurance
301089,Bay Area Crane Service Inc,bayareacrane.com,industrial machinery manufacturing,1-10,NaN,Houston,Texas,US,Manufacturing & Industrial
2064638,Nuestra Visión,nuestravision.tv,broadcast media production and distribution,51-200,Public Company,Miami,Florida,US,Media & Publishing
1627023,Taubman Center for State & Local Government,harvard.edu,higher education,11-50,Educational,Cambridge,Massachusetts,US,Education
1844161,Prompt Digital,promptdigital.io,"technology, information and internet",1-10,Privately Held,San Francisco,California,US,Technology & Digital
1609076,Gordon Property Management,gpmsf.com,real estate,1-10,Privately Held,San Francisco,California,US,Construction & Real Estate
2352265,Grette Associates LLC,gretteassociates.com,environmental services,11-50,Partnership,Wenatchee,Washington,US,Energy & Environment
2529086,"Business Data Applications, Inc.",healthycontracts.com,it services and it consulting,11-50,Privately Held,Exeter,New Hampshire,US,Technology & Digital
3015122,Customs & Classics Auto World,customsandclassicsautoworld.com,motor vehicle manufacturing,1-10,Public Company,Otsego,Minnesota,US,Manufacturing & Industrial
1266487,Care Net Pregnancy Center of Frederick,carenetfrederick.org,medical practices,11-50,NaN,Frederick,Maryland,US,Healthcare
1663120,St. Plant,stplant.co,retail,1-10,Privately Held,Washington,District Of Columbia,US,Commerce & Consumer
1056473,Kwfc Radio,kwfc.org,graphic design,1-10,NaN,Springfield,Missouri,US,Arts & Design
487895,BridgeSocial,bridgesocialmedia.com,advertising services,1-10,Privately Held,Seattle,Washington,US,Marketing & Communications
1427275,Katherine Johnson Law LLC,katherinejohnsonlaw.com,law practice,1-10,Privately Held,Chicago,Illinois,US,Legal & Professional Services
2317456,INKollective,inkollective.com,apparel & fashion,1-10,Privately Held,Rolla,Missouri,US,Commerce & Consumer
2590211,Sheriff Plumbing,sheriffplumbing.com,building materials,1-10,NaN,Rancho Cucamonga,California,US,Construction & Real Estate
1849855,Team BRIDGES,bridgesusa.org,education administration programs,11-50,Nonprofit,Memphis,Tennessee,US,Education
1648896,"Incite Strategic Partners, LLC",incitesp.com,hospitals and health care,11-50,Partnership,Lake Oswego,Oregon,US,Healthcare
2547470,OMAX Oral & Maxillofacial Surgery,omaxsurgery.com,hospitals and health care,11-50,Privately Held,Spokane Valley,Washington,US,Healthcare
332490,"Vex Intel, LLC",archive.org,security and investigations,1-10,Privately Held,Tampa,Florida,US,Legal & Professional Services
1358179,Noe Import Auto,noeimports.com,food and beverage services,1-10,NaN,Mesa,Arizona,US,Hospitality & Travel
737852,Traverse Anesthesia Assoc P C,taapc.org,medical practices,11-50,NaN,Traverse City,Michigan,US,Healthcare
1134011,Miracle Ear Hearing Centers,miraclear.com,hospitals and health care,11-50,Public Company,Janesville,Wisconsin,US,Healthcare
213333,Riffle Contracting,rifflecontracting.com,construction,1-10,NaN,Hurst,Texas,US,Construction & Real Estate
1989424,Nevada Linen Supply,nevadalinen.com,hospitality,51-200,Privately Held,Las Vegas,Nevada,US,Hospitality & Travel
1166983,"Just Books Publishing, L.L.C",justbookspublishing.com,book and periodical publishing,1-10,Public Company,Zephyrhills,Florida,US,Media & Publishing

In [4]:
url_access = sample["website"].apply(validate_website)
access_results = pd.DataFrame(url_access.tolist())

In [5]:
access_results

,accessible,http_status,final_url,content_type,failure_reason,website_type
0,True,200.0,https://nigerianvisaservices.com/,text/html,NaN,company_website
1,True,200.0,https://husldigital.com/,text/html; charset=UTF-8,NaN,company_website
2,False,403.0,https://baitshoppe.com/,text/html,http_error,NaN
3,False,NaN,NaN,NaN,connection_error,NaN
4,True,200.0,https://medrankinteractive.com/,text/html; charset=UTF-8,NaN,company_website
5,True,200.0,https://www.newstylemotherlode.com/,text/html; charset=UTF-8,NaN,company_website
6,True,200.0,https://www.globalfashionxchange.org/,text/html; charset=UTF-8,NaN,company_website
7,True,200.0,https://www.htts.com/,text/html; charset=UTF-8,NaN,company_website
8,False,NaN,NaN,NaN,connection_error,NaN
9,True,200.0,https://mjobookkeeper.com/,text/html,NaN,company_website
10,True,200.0,https://kirschnercontractors.com/,text/html; charset=UTF-8,NaN,company_website
11,True,200.0,https://www.dalefesteautomotive.com/,text/html; charset=UTF-8,NaN,company_website
12,False,NaN,NaN,NaN,connection_error,NaN
13,False,NaN,NaN,NaN,connection_error,NaN
14,False,NaN,NaN,NaN,connection_error,NaN
15,False,NaN,NaN,NaN,connection_error,NaN
16,False,403.0,https://nuestravision.tv/,text/html,http_error,NaN
17,True,200.0,https://www.harvard.edu/,text/html; charset=UTF-8,NaN,company_website
18,True,200.0,https://www.qontour.com/,text/html; charset=utf-8,NaN,company_website
19,False,403.0,https://gpmsf.com/,text/html,http_error,NaN
20,False,403.0,https://gretteassociates.com/,text/html; charset=iso-8859-1,http_error,NaN
21,True,200.0,https://www.healthycontracts.com/,text/html; charset=UTF-8,NaN,company_website
22,False,NaN,NaN,NaN,connection_error,NaN
23,False,403.0,https://carenetfrederick.org/,text/html,http_error,NaN
24,False,404.0,https://www.stplant.co/,text/html;charset=utf-8,http_error,NaN
25,True,200.0,https://kwfc.org/,text/html; charset=UTF-8,NaN,company_website
26,True,200.0,https://bridgesocialmedia.com/,text/html; charset=utf-8,NaN,company_website
27,True,200.0,https://katherinejohnsonlaw.com/,text/html,NaN,company_website
28,True,200.0,https://www.inkollective.com/,text/html; charset=UTF-8,NaN,company_website
29,False,NaN,NaN,NaN,connection_error,NaN
30,True,200.0,https://bridgesusa.org/,text/html; charset=utf-8,NaN,company_website
31,True,200.0,https://incitesp.com/,text/html; charset=UTF-8,NaN,company_website
32,True,200.0,https://www.omaxsurgery.com/,text/html; charset=utf-8,NaN,company_website
33,True,200.0,https://archive.org/,text/html; charset=utf-8,NaN,directory
34,True,200.0,https://noeimports.com/,text/html; charset=UTF-8,NaN,company_website
35,True,200.0,https://taapc.org/en,text/html; charset=utf-8,NaN,company_website
36,False,465.0,http://www.dynamo.com/assets.htm,text/html; charset=utf-8,http_error,NaN
37,True,200.0,https://www.rifflecontracting.com/,text/html; charset=UTF-8,NaN,company_website
38,False,403.0,https://www.imagefirst.com/nevada-linen-supply/,text/html,http_error,NaN
39,False,NaN,NaN,NaN,connection_error,NaN

In [6]:
success = access_results[access_results["website_type"] == "company_website"]
success

,accessible,http_status,final_url,content_type,failure_reason,website_type
0,True,200.0,https://nigerianvisaservices.com/,text/html,NaN,company_website
1,True,200.0,https://husldigital.com/,text/html; charset=UTF-8,NaN,company_website
4,True,200.0,https://medrankinteractive.com/,text/html; charset=UTF-8,NaN,company_website
5,True,200.0,https://www.newstylemotherlode.com/,text/html; charset=UTF-8,NaN,company_website
6,True,200.0,https://www.globalfashionxchange.org/,text/html; charset=UTF-8,NaN,company_website
7,True,200.0,https://www.htts.com/,text/html; charset=UTF-8,NaN,company_website
9,True,200.0,https://mjobookkeeper.com/,text/html,NaN,company_website
10,True,200.0,https://kirschnercontractors.com/,text/html; charset=UTF-8,NaN,company_website
11,True,200.0,https://www.dalefesteautomotive.com/,text/html; charset=UTF-8,NaN,company_website
17,True,200.0,https://www.harvard.edu/,text/html; charset=UTF-8,NaN,company_website
18,True,200.0,https://www.qontour.com/,text/html; charset=utf-8,NaN,company_website
21,True,200.0,https://www.healthycontracts.com/,text/html; charset=UTF-8,NaN,company_website
25,True,200.0,https://kwfc.org/,text/html; charset=UTF-8,NaN,company_website
26,True,200.0,https://bridgesocialmedia.com/,text/html; charset=utf-8,NaN,company_website
27,True,200.0,https://katherinejohnsonlaw.com/,text/html,NaN,company_website
28,True,200.0,https://www.inkollective.com/,text/html; charset=UTF-8,NaN,company_website
30,True,200.0,https://bridgesusa.org/,text/html; charset=utf-8,NaN,company_website
31,True,200.0,https://incitesp.com/,text/html; charset=UTF-8,NaN,company_website
32,True,200.0,https://www.omaxsurgery.com/,text/html; charset=utf-8,NaN,company_website
34,True,200.0,https://noeimports.com/,text/html; charset=UTF-8,NaN,company_website
35,True,200.0,https://taapc.org/en,text/html; charset=utf-8,NaN,company_website
37,True,200.0,https://www.rifflecontracting.com/,text/html; charset=UTF-8,NaN,company_website

In [7]:
len(success)

22

In [8]:
typography_results = await load_page(success["final_url"].iloc[0])

typography_results

{'url': 'https://nigerianvisaservices.com/',
 'scrape_status': 'success',
 'failure_reason': None,
 'elements': [{'tag': 'h3',
   'text': 'Verifying that you are not a robot...',
   'text_length': 37,
   'x': 427.5,
   'y': 166.390625,
   'width': 425,
   'height': 28,
   'font_family': 'Times',
   'font_size': '24px',
   'font_weight': '100',
   'line_height': 'normal',
   'letter_spacing': 'normal',
   'text_transform': 'none',
   'text_align': 'center',
   'visible': True,
   'element_index': 1}]}

In [9]:
urls = success["final_url"].tolist()

typography_results_all = await asyncio.gather(
    *(load_page(url) for url in urls)
)

In [10]:
df_typ_results = pd.DataFrame(typography_results_all)
df_typ_results

,url,scrape_status,failure_reason,elements
0,https://nigerianvisaservices.com/,success,None,"[{'tag': 'h3', 'text': 'Verifying that you are..."
1,https://husldigital.com/,success,None,"[{'tag': 'h1', 'text': 'Digital + AI solutions..."
2,https://medrankinteractive.com/,success,None,"[{'tag': 'p', 'text': 'Want a FREE Website Bef..."
3,https://www.newstylemotherlode.com/,success,None,"[{'tag': 'p', 'text': 'HOME', 'text_length': 4..."
4,https://www.globalfashionxchange.org/,success,None,"[{'tag': 'p', 'text': 'HOME', 'text_length': 4..."
5,https://www.htts.com/,success,None,"[{'tag': 'span', 'text': 'Contact Us', 'text_l..."
6,https://mjobookkeeper.com/,success,None,"[{'tag': 'div', 'text': 'prev', 'text_length':..."
7,https://kirschnercontractors.com/,success,None,"[{'tag': 'h1', 'text': 'DELIVERING PROJECTS ON..."
8,https://www.dalefesteautomotive.com/,success,None,"[{'tag': 'p', 'text': 'Monday – Friday 7am – 5..."
9,https://www.harvard.edu/,success,None,"[{'tag': 'span', 'text': 'Harvard University',..."
10,https://www.qontour.com/,success,None,"[{'tag': 'div', 'text': 'Ecosystem', 'text_len..."
11,https://www.healthycontracts.com/,success,None,"[{'tag': 'span', 'text': 'Geek Blog', 'text_le..."
12,https://kwfc.org/,success,None,"[{'tag': 'div', 'text': 'KWFC', 'text_length':..."
13,https://bridgesocialmedia.com/,success,None,"[{'tag': 'span', 'text': '🏠', 'text_length': 2..."
14,https://katherinejohnsonlaw.com/,success,None,[]
15,https://www.inkollective.com/,success,None,"[{'tag': 'span', 'text': 'Video Player', 'text..."
16,https://bridgesusa.org/,success,None,"[{'tag': 'div', 'text': 'Interested in youth p..."
17,https://incitesp.com/,success,None,"[{'tag': 'span', 'text': 'Solutions', 'text_le..."
18,https://www.omaxsurgery.com/,success,None,"[{'tag': 'h1', 'text': 'Dr. Daniel W. Skinner'..."
19,https://noeimports.com/,success,None,"[{'tag': 'span', 'text': 'Home', 'text_length'..."
20,https://taapc.org/en,success,None,"[{'tag': 'div', 'text': 'المجلس البرلماني الآس..."
21,https://www.rifflecontracting.com/,success,None,"[{'tag': 'div', 'text': 'TrayCeiling', 'text_l..."

In [16]:
typography_results_all[9]

{'url': 'https://www.harvard.edu/',
 'scrape_status': 'success',
 'failure_reason': None,
 'elements': [{'tag': 'span',
   'text': 'Harvard University',
   'text_length': 18,
   'x': 39,
   'y': 20,
   'width': 1,
   'height': 1,
   'font_family': '"GT America Standard Regular"',
   'font_size': '18px',
   'font_weight': '400',
   'line_height': '0px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 5},
  {'tag': 'span',
   'text': 'Search',
   'text_length': 6,
   'x': 1021.828125,
   'y': 31.5,
   'width': 56.140625,
   'height': 27,
   'font_family': '"GT America Standard Regular"',
   'font_size': '18px',
   'font_weight': '400',
   'line_height': '27px',
   'letter_spacing': '-0.1px',
   'text_transform': 'none',
   'text_align': 'center',
   'visible': True,
   'element_index': 14},
  {'tag': 'span',
   'text': 'Menu',
   'text_length': 4,
   'x': 1195.15625,
   'y': 31.5,
   'width': 45.84375,
   'height': 27,
   'font_family': '"GT America Standard Regular"',
   'font_size': '18px',
   'font_weight': '400',
   'line_height': '27px',
   'letter_spacing': '-0.1px',
   'text_transform': 'none',
   'text_align': 'center',
   'visible': True,
   'element_index': 29},
  {'tag': 'h1',
   'text': 'Harvard University',
   'text_length': 18,
   'x': -1,
   'y': -1,
   'width': 1,
   'height': 1,
   'font_family': '"GT America Standard Regular"',
   'font_size': '36px',
   'font_weight': '400',
   'line_height': '54px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 317},
  {'tag': 'h2',
   'text': 'Transformative Treatments',
   'text_length': 25,
   'x': 128,
   'y': 236,
   'width': 1024,
   'height': 65.28125,
   'font_family': '"Canela Deck Web"',
   'font_size': '54.4px',
   'font_weight': '400',
   'line_height': '65.28px',
   'letter_spacing': '-0.55px',
   'text_transform': 'none',
   'text_align': 'center',
   'visible': True,
   'element_index': 324},
  {'tag': 'p',
   'text': 'Using innovative approaches, advanced research, and nanotechnology, Harvard scientists are finding new ways to treat Alzheimer’s, cancer, diabetes, and more.',
   'text_length': 157,
   'x': 328,
   'y': 333.28125,
   'width': 624,
   'height': 81,
   'font_family': '"GT America Standard Regular"',
   'font_size': '18px',
   'font_weight': '400',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'center',
   'visible': True,
   'element_index': 325},
  {'tag': 'h2',
   'text': 'New approaches to long-standing illnesses',
   'text_length': 41,
   'x': 72,
   'y': 806.28125,
   'width': 568,
   'height': 130.5625,
   'font_family': '"Canela Deck Web"',
   'font_size': '54.4px',
   'font_weight': '400',
   'line_height': '65.28px',
   'letter_spacing': '-0.55px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 329},
  {'tag': 'span',
   'text': 'Alzheimer’s',
   'text_length': 11,
   'x': 104,
   'y': 1367.625,
   'width': 157.53125,
   'height': 40,
   'font_family': '"Canela Deck Web"',
   'font_size': '31.68px',
   'font_weight': '400',
   'line_height': '36.432px',
   'letter_spacing': '-0.1px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 338},
  {'tag': 'p',
   'text': 'Bruce Yankner and his team published research showing that lithium is a natural, biologically important element in the brain that has the potential to prevent or even reverse Alzheimer’s disease.',
   'text_length': 195,
   'x': 104,
   'y': 1422.0625,
   'width': 282.65625,
   'height': 162,
   'font_family': '"GT America Standard Regular"',
   'font_size': '18px',
   'font_weight': '400',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 340},
  {'tag': 'span',
   'text': 'Learn more about the breakthrough',
   'text_length': 33,
   'x': 156,
   'y': 1682.0625,
   'width': 174.03125,
   'height': 50,
   'font_family': '"GT America Standard Medium"',
   'font_size': '18px',
   'font_weight': '500',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'left',
   'visible': True,
   'element_index': 343},
  {'tag': 'span',
   'text': 'ALS',
   'text_length': 3,
   'x': 498.65625,
   'y': 1367.625,
   'width': 57.359375,
   'height': 40,
   'font_family': '"Canela Deck Web"',
   'font_size': '31.68px',
   'font_weight': '400',
   'line_height': '36.432px',
   'letter_spacing': '-0.1px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 350},
  {'tag': 'p',
   'text': 'After three decades researching amyotrophic lateral sclerosis, also known as Lou Gehrig’s disease, Merit Cudkowicz says a new drug shows “the whole field that this illness can be stopped.”',
   'text_length': 188,
   'x': 498.65625,
   'y': 1422.0625,
   'width': 282.65625,
   'height': 162,
   'font_family': '"GT America Standard Regular"',
   'font_size': '18px',
   'font_weight': '400',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 352},
  {'tag': 'span',
   'text': 'Learn more about the advance',
   'text_length': 28,
   'x': 550.65625,
   'y': 1682.0625,
   'width': 174.03125,
   'height': 50,
   'font_family': '"GT America Standard Medium"',
   'font_size': '18px',
   'font_weight': '500',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'left',
   'visible': True,
   'element_index': 355},
  {'tag': 'span',
   'text': 'Diabetes',
   'text_length': 8,
   'x': 893.3125,
   'y': 1367.625,
   'width': 121.875,
   'height': 40,
   'font_family': '"Canela Deck Web"',
   'font_size': '31.68px',
   'font_weight': '400',
   'line_height': '36.432px',
   'letter_spacing': '-0.1px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 362},
  {'tag': 'p',
   'text': 'More than three decades ago, Joel Habener set up an experiment at Massachusetts General Hospital that led to the discovery of GLP-1, a hormone now used to treat diabetes and obesity.',
   'text_length': 182,
   'x': 893.3125,
   'y': 1422.0625,
   'width': 282.65625,
   'height': 162,
   'font_family': '"GT America Standard Regular"',
   'font_size': '18px',
   'font_weight': '400',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 364},
  {'tag': 'span',
   'text': 'Learn more about the discovery',
   'text_length': 30,
   'x': 945.3125,
   'y': 1682.0625,
   'width': 174.03125,
   'height': 50,
   'font_family': '"GT America Standard Medium"',
   'font_size': '18px',
   'font_weight': '500',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'left',
   'visible': True,
   'element_index': 367},
  {'tag': 'h3',
   'text': 'Cancer',
   'text_length': 6,
   'x': 120,
   'y': 2042.0625,
   'width': 552,
   'height': 65.28125,
   'font_family': '"Canela Deck Web"',
   'font_size': '54.4px',
   'font_weight': '400',
   'line_height': '65.28px',
   'letter_spacing': '-0.55px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 379},
  {'tag': 'p',
   'text': 'Harvard scientists are finding powerful new ways to diagnose and treat cancer, including creating , using CAR-T-cell therapy to , blocking a specific protein to , and with a novel drug.',
   'text_length': 185,
   'x': 120,
   'y': 2123.34375,
   'width': 552,
   'height': 162,
   'font_family': '"GT America Standard Regular"',
   'font_size': '18px',
   'font_weight': '400',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 382},
  {'tag': 'span',
   'text': 'Learn about more cancer breakthroughs',
   'text_length': 37,
   'x': 172,
   'y': 2319.34375,
   'width': 326.65625,
   'height': 23,
   'font_family': '"GT America Standard Medium"',
   'font_size': '18px',
   'font_weight': '500',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'left',
   'visible': True,
   'element_index': 384},
  {'tag': 'h2',
   'text': 'From our labs to\xa0your\xa0life',
   'text_length': 26,
   'x': 24,
   'y': 2644.34375,
   'width': 616,
   'height': 113,
   'font_family': '"Canela Deck Web"',
   'font_size': '42.24px',
   'font_weight': '400',
   'line_height': '50.688px',
   'letter_spacing': '-0.45px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 386},
  {'tag': 'span',
   'text': 'Learn more about how groundbreaking medicine becomes accessible to the public',
   'text_length': 77,
   'x': 716,
   'y': 2678.34375,
   'width': 314.125,
   'height': 77,
   'font_family': '"GT America Standard Medium"',
   'font_size': '18px',
   'font_weight': '500',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'left',
   'visible': True,
   'element_index': 389},
  {'tag': 'span',
   'text': 'Doug Melton on his research journey',
   'text_length': 35,
   'x': 159,
   'y': 3257.734375,
   'width': 415.921875,
   'height': 33.59375,
   'font_family': '"Canela Deck Web"',
   'font_size': '24px',
   'font_weight': '400',
   'line_height': '33.6px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'left',
   'visible': True,
   'element_index': 397},
  {'tag': 'h3',
   'text': 'New developments for type 1 diabetes',
   'text_length': 36,
   'x': 680,
   'y': 3032.859375,
   'width': 528,
   'height': 101.34375,
   'font_family': '"Canela Deck Web"',
   'font_size': '42.24px',
   'font_weight': '400',
   'line_height': '50.688px',
   'letter_spacing': '-0.45px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 400},
  {'tag': 'p',
   'text': 'Inspired by his son’s diagnosis with type 1 diabetes, Harvard Professor Doug Melton shifted his lab’s focus to finding a cure through pioneering work on stem cells.',
   'text_length': 164,
   'x': 680,
   'y': 3150.203125,
   'width': 528,
   'height': 81,
   'font_family': '"GT America Standard Regular"',
   'font_size': '18px',
   'font_weight': '400',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 403},
  {'tag': 'span',
   'text': 'Learn more about his work on diabetes',
   'text_length': 37,
   'x': 732,
   'y': 3265.203125,
   'width': 314.59375,
   'height': 23,
   'font_family': '"GT America Standard Medium"',
   'font_size': '18px',
   'font_weight': '500',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'left',
   'visible': True,
   'element_index': 405},
  {'tag': 'p',
   'text': 'Harvard alum Manny Simons and his company  Akouos led a groundbreaking trial for congenital deafness that enabled an 11-year-old boy to hear for the first time.',
   'text_length': 160,
   'x': 564,
   'y': 3385.90625,
   'width': 468,
   'height': 81,
   'font_family': '"GT America Standard Regular"',
   'font_size': '18px',
   'font_weight': '400',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 412},
  {'tag': 'p',
   'text': 'Kinvard Bio, a biotechnology company launched out of Harvard’s Myers Lab, is creating a new class of antibiotics in the hopes of treating drug-resistant infections and diseases.',
   'text_length': 177,
   'x': 564,
   'y': 3641.28125,
   'width': 468,
   'height': 108,
   'font_family': '"GT America Standard Regular"',
   'font_size': '18px',
   'font_weight': '400',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 418},
  {'tag': 'p',
   'text': 'Researchers at Harvard’s Wyss Institute are harnessing DNA nanotechnology to deliver drugs for cancer, autoimmune diseases, and infectious diseases with nanoscale precision.',
   'text_length': 173,
   'x': 564,
   'y': 3896.65625,
   'width': 468,
   'height': 108,
   'font_family': '"GT America Standard Regular"',
   'font_size': '18px',
   'font_weight': '400',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 424},
  {'tag': 'h2',
   'text': 'Saving the brain through science',
   'text_length': 32,
   'x': 24,
   'y': 4187.84375,
   'width': 616,
   'height': 101.34375,
   'font_family': '"Canela Deck Web"',
   'font_size': '42.24px',
   'font_weight': '400',
   'line_height': '50.688px',
   'letter_spacing': '-0.45px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 427},
  {'tag': 'span',
   'text': 'Using AI to find treatments for Rett Syndrome',
   'text_length': 45,
   'x': 104,
   'y': 4963.0625,
   'width': 260.765625,
   'height': 112.875,
   'font_family': '"Canela Deck Web"',
   'font_size': '31.68px',
   'font_weight': '400',
   'line_height': '36.432px',
   'letter_spacing': '-0.1px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 437},
  {'tag': 'p',
   'text': 'AI-enabled drug discovery identified a potentially game-changing treatment that’s been advanced from the lab bench to an FDA Orphan Drug Designation in record time.',
   'text_length': 164,
   'x': 104,
   'y': 5090.375,
   'width': 282.65625,
   'height': 162,
   'font_family': '"GT America Standard Regular"',
   'font_size': '18px',
   'font_weight': '400',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 439},
  {'tag': 'span',
   'text': 'Learn more about the discovery',
   'text_length': 30,
   'x': 156,
   'y': 5092.375,
   'width': 174.03125,
   'height': 50,
   'font_family': '"GT America Standard Medium"',
   'font_size': '18px',
   'font_weight': '500',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'left',
   'visible': True,
   'element_index': 442},
  {'tag': 'span',
   'text': 'Predicting suicide attempts a week in advance',
   'text_length': 45,
   'x': 498.65625,
   'y': 4963.0625,
   'width': 253.265625,
   'height': 112.875,
   'font_family': '"Canela Deck Web"',
   'font_size': '31.68px',
   'font_weight': '400',
   'line_height': '36.432px',
   'letter_spacing': '-0.1px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 449},
  {'tag': 'p',
   'text': 'Psychologist Matthew Nock’s research using real-time surveys forecasted 87% of suicide-related crises before they occurred—a marked leap beyond existing prediction models.',
   'text_length': 171,
   'x': 498.65625,
   'y': 5090.375,
   'width': 282.65625,
   'height': 162,
   'font_family': '"GT America Standard Regular"',
   'font_size': '18px',
   'font_weight': '400',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 451},
  {'tag': 'span',
   'text': 'Learn about the improved predictions',
   'text_length': 36,
   'x': 550.65625,
   'y': 5092.375,
   'width': 208.21875,
   'height': 50,
   'font_family': '"GT America Standard Medium"',
   'font_size': '18px',
   'font_weight': '500',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'left',
   'visible': True,
   'element_index': 454},
  {'tag': 'span',
   'text': 'Marking a milestone toward prion disease treatment',
   'text_length': 50,
   'x': 893.3125,
   'y': 4963.0625,
   'width': 278.375,
   'height': 112.875,
   'font_family': '"Canela Deck Web"',
   'font_size': '31.68px',
   'font_weight': '400',
   'line_height': '36.432px',
   'letter_spacing': '-0.1px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 461},
  {'tag': 'p',
   'text': 'Recent research provides hope that prion disease—a handful of rare disorders caused by misfolded proteins in the brain—may soon have a treatment or even a cure.',
   'text_length': 160,
   'x': 893.3125,
   'y': 5090.375,
   'width': 282.65625,
   'height': 135,
   'font_family': '"GT America Standard Regular"',
   'font_size': '18px',
   'font_weight': '400',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 463},
  {'tag': 'span',
   'text': 'Learn how gene editing may be the solution',
   'text_length': 42,
   'x': 945.3125,
   'y': 5092.375,
   'width': 226.15625,
   'height': 50,
   'font_family': '"GT America Standard Medium"',
   'font_size': '18px',
   'font_weight': '500',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'left',
   'visible': True,
   'element_index': 466},
  {'tag': 'h2',
   'text': 'Award-winning research',
   'text_length': 22,
   'x': 24,
   'y': 5151.5625,
   'width': 616,
   'height': 50.671875,
   'font_family': '"Canela Deck Web"',
   'font_size': '42.24px',
   'font_weight': '400',
   'line_height': '50.688px',
   'letter_spacing': '-0.45px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 468},
  {'tag': 'h3',
   'text': 'Autism research',
   'text_length': 15,
   'x': 1065.8125,
   'y': 5494.4375,
   'width': 416,
   'height': 38.015625,
   'font_family': '"Canela Deck Web"',
   'font_size': '31.68px',
   'font_weight': '400',
   'line_height': '38.016px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 480},
  {'tag': 'div',
   'text': 'Paola Arlotta was awarded an ARIA grant for her work with artificial intelligence and brain-mimicking “organoids” to better understand autism.',
   'text_length': 142,
   'x': 1065.8125,
   'y': 5548.453125,
   'width': 416,
   'height': 81,
   'font_family': '"GT America Standard Regular"',
   'font_size': '18px',
   'font_weight': '400',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 481},
  {'tag': 'span',
   'text': "Learn more about Paola's work",
   'text_length': 29,
   'x': 1117.8125,
   'y': 5654.640625,
   'width': 248.34375,
   'height': 23,
   'font_family': '"GT America Standard Medium"',
   'font_size': '18px',
   'font_weight': '500',
   'line_height': '27px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'left',
   'visible': True,
   'element_index': 482},
  {'tag': 'h3',
   'text': 'Genetic disorders',
   'text_length': 17,
   'x': 2114.612548828125,
   'y': 5480.9375,
   'width': 416,
   'height': 38.015625,
   'font_family': '"Canela Deck Web"',
   'font_size': '31.68px',
   'font_weight': '400',
   'line_height': '38.016px',
   'letter_spacing': '-0.25px',
   'text_transform': 'none',
   'text_align': 'start',
   'visible': True,
   'element_index': 487},
  {'tag': 'div',
   'text': 'David Liu has been named a laureate of the 2025 Breakthrough Prize in Life Sciences for the development of gene-editing platforms, which can correct disease-causing genetic variations.',
   'text_length': 184,
   'x': 2114.612548828125,
   'y': 5534.953125,
   'width': 416,
   'height': 108,